base_url = "https://van-sprundel.org"
title = "Ramon van Sprundel"
description = "Rust enthusiast"
compile_sass = true
build_search_index = false
theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true

[extra]
theme = "light"
socials = [
  { name = "github", url = "https://github.com/van-sprundel/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/ramon-van-sprundel-6456701b1/", icon = "linkedin" },
]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]
comments = true
